#!/usr/bin/env python3
"""ADR-0074 sprint γ: PMDDOTNET_MML preflight song_table extension generator.

PMDDotNET .M / .MN binary part offset table (= bytes 1..22 LE 16-bit × 11
entries A-K + bytes 23..24 extended_data_adr for L-Q) を parse し、 song_data.inc
に挿入する 20 entries `.dw` column + song2_part_X label `==` 絶対 equate 定義
を生成する。

driver `src/driver/standalone_test.s` L6188-6264 (= pmdneo_mn_direct_load_k_part_addr
+ pmdneo_mn_direct_load_aj_part_addr) と同 part offset 解釈 logic:
  pmddotnet_song[0]      = m_start
  pmddotnet_song[1..2]   = m_buf[0..1]   = part A offset (LE 16-bit)
  pmddotnet_song[3..4]   = part B offset
  ...
  pmddotnet_song[21..22] = m_buf[20..21] = part K offset (LE 16-bit)
  pmddotnet_song[23..24] = m_buf[22..23] = extended_data_adr (= rhythm/L-Q table)

song2_part_X 経路 = pmddotnet_song + 1 + part_X_offset。

L-Q + X/Y/Z (= PMDDotNET .M format 上は extended_data_adr 経由か未表現) は
preflight 用に part A offset を流用 (= PMDDotNET output が unused part に
emit する empty 終端 body 経路の安全 fallback)、 preflight fixture (= 例 =
preflight-staggered.mml) で実際に走らせる part のみ正規 offset で dispatch。
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path


PART_ORDER = [
    "a", "b", "c", "d", "e",
    "f", "g", "h", "i", "j",
    "k", "l", "m", "n", "o",
    "p", "q", "x", "y", "z",
]


def parse_part_offsets(data: bytes) -> tuple[dict[str, int], list[tuple[int, int, int]]]:
    """Parse A-K part offsets from .M header bytes 1..22 (LE 16-bit × 11)."""
    if len(data) < 23:
        sys.exit(
            f"ERROR: input .m binary too short ({len(data)} byte, need >= 23 for A-K header)"
        )
    parts_ak = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]
    offsets: dict[str, int] = {}
    byte_records: list[tuple[int, int, int]] = []
    for i, p in enumerate(parts_ak):
        lo_idx = 1 + i * 2
        hi_idx = 2 + i * 2
        lo = data[lo_idx]
        hi = data[hi_idx]
        value = (hi << 8) | lo
        offsets[p] = value
        byte_records.append((lo_idx, lo, hi))
    return offsets, byte_records


def fill_unused_parts(offsets: dict[str, int]) -> None:
    """L-Q + X/Y/Z は extended_data_adr 経由か未表現のため part A offset を流用。

    PMDDotNET output は MML で specify されない part にも minimal terminator
    body を emit するため、 part A offset 流用は preflight 経路で safe 動作する
    (= preflight fixture は実際に走る part のみ正規 audible expected、 未使用
    part body は driver で即終端遭遇)。
    """
    fallback = offsets["a"]
    for p in ["l", "m", "n", "o", "p", "q", "x", "y", "z"]:
        offsets[p] = fallback


def emit_inc(
    offsets: dict[str, int],
    byte_records: list[tuple[int, int, int]],
    label_prefix: str,
    song_label: str,
    source_basename: str,
    source_size: int,
) -> str:
    lines: list[str] = []
    lines.append(
        ";; ADR-0074 sprint γ: PMDDOTNET_MML preflight song slot "
        "(= TEST_MODE_PMDDOTNET_SONG_SELECT=1)"
    )
    lines.append(
        f";; Generated by scripts/pmddotnet-song-table-entries.py "
        f"(source: {source_basename}, {source_size} byte)"
    )
    lines.append(
        ";; song_table[40..59] = song2_part_a〜z entries (= driver_song_id=2 dispatch 経路)"
    )

    rows = [
        PART_ORDER[0:4],
        PART_ORDER[4:8],
        PART_ORDER[8:12],
        PART_ORDER[12:16],
        PART_ORDER[16:20],
    ]
    for row in rows:
        cols = ", ".join(f"{label_prefix}_{p}" for p in row)
        lines.append(f"        .dw {cols}")
    lines.append("")
    lines.append(";; song2_part_X label 絶対 equate (= pmddotnet_song + 1 + part_X_offset)")
    lines.append(
        ";; A-K = parsed from .m header bytes 1-22 (LE 16-bit × 11、 driver L6195-6206 layout 整合)"
    )
    lines.append(
        ";; L-Q + X/Y/Z = part A offset 流用 (= PMDDotNET unused part empty body fallback、 preflight scope)"
    )
    for p in PART_ORDER:
        lines.append(f"{label_prefix}_{p}   ==   {song_label} + 1 + 0x{offsets[p]:04x}")

    lines.append("")
    lines.append(";; Byte origin verifier (= ADR-0074 sprint β round 2 LR-1 反映、")
    lines.append(";;  helper script byte origin literal record、 γ-3 .lst predicate 追加候補):")
    parts_ak = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]
    for p, (lo_idx, lo, hi) in zip(parts_ak, byte_records):
        lines.append(
            f";;   part {p}: bytes[{lo_idx:2d}..{lo_idx+1:2d}] = "
            f"0x{lo:02x} 0x{hi:02x} → LE = 0x{offsets[p]:04x}"
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--input", required=True, help="PMDDotNET .M / .MN binary path")
    ap.add_argument("--output", required=True, help="Generated .inc output path")
    ap.add_argument(
        "--label-prefix",
        default="song2_part",
        help="song_table entry label prefix (default: song2_part)",
    )
    ap.add_argument(
        "--song-label",
        default="pmddotnet_song",
        help="Base label for .m incbin (default: pmddotnet_song)",
    )
    args = ap.parse_args()

    src = Path(args.input)
    if not src.is_file():
        sys.exit(f"ERROR: input not found: {src}")
    data = src.read_bytes()

    offsets, byte_records = parse_part_offsets(data)
    fill_unused_parts(offsets)
    text = emit_inc(
        offsets,
        byte_records,
        args.label_prefix,
        args.song_label,
        src.name,
        len(data),
    )
    Path(args.output).write_text(text, encoding="utf-8")

    summary = ", ".join(f"{p}=0x{offsets[p]:04x}" for p in ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k"])
    print(
        f"[pmddotnet-song-table-entries] wrote {args.output} "
        f"(A-K offsets: {summary})",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
